[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Next.js specific configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables setup instructions
[context.production.environment]
  # Add your production environment variables here
  # NEXT_PUBLIC_SUPABASE_URL = "your-production-supabase-url"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-production-supabase-anon-key"

# Redirects for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https:; connect-src 'self' https://*.supabase.co https://*.supabase.in;"
